# Generated by Django 2.2.16 on 2021-04-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impiegato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Impiegato',
        ),
    ]
